image: archlinux

packages:
  - podman

sources:
  - https://github.com/innereq/lenny

tasks:
  - test: |
      echo "Hello!"
      whoami
      ls -la
  - build: |
      podman run -it --rm -v ./lenny:/lenny gcr.io/kaniko-project/executor:debug --context /lenny --dockerfile /lenny/docker/prod/Dockerfile --no-push --force
