image: fedora/32

packages:
  - podman

sources:
  - https://github.com/innereq/lenny

secrets:
  - a2e68d5a-6dc3-417e-89b0-fde0d184bdc5

tasks:
  - build: |
      podman run -it --rm -v ./lenny:/lenny -v ./.docker:/kaniko/.docker gcr.io/kaniko-project/executor:debug --force --cache=true --context /lenny --dockerfile /lenny/docker/prod/Dockerfile --destination lula.moonbutt.science/innereq/containers/lenny:`cd lenny && git log --format="%H" -n 1 | cut -b1-8 -`