name: "Continuous Integration"

on: 
  push:
    branches:
      - downstream
  pull_request:
    branches:
      - downstream

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    env:
      DATABASE_URL: "postgres://lenny:password@localhost:5432/lenny"
      LEMMY_DATABASE_URL: "postgres://lenny:password@localhost:5432/lenny"
      RUST_TEST_THREADS: 1
    
    services:
      db:
        image: postgres:alpine
        ports: ['5432:5432']
        env:
          POSTGRES_USER: lenny
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - name: "Install Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: "rustfmt, clippy"

      - name: "Build backend code"
        run: |
          cargo build

      - name: "Lint backend code"
        run: |
          cargo clippy -- -D clippy::style -D clippy::correctness -D clippy::complexity -D clippy::perf
      
      - name: "Run backend migrations"
        run: |
          cargo install diesel_cli --no-default-features --features postgres --force
          diesel migration run

      - name: "Run backend tests"
        run: |
          sudo apt-get install espeak
          cargo test --workspace

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    steps:
      - uses: actions/checkout@v2

      - name: "Install Node toolchain"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: "Build frontend code"
        run: |
          yarn
          yarn build

      - name: "Lint frontend code"
        run: |
          yarn lint